<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sword" failures="8" tests="18" name="UnitTests" time="414.571" errors="0" timestamp="02 Apr 2021 04:28:46 GMT">
  <testcase classname="FactoryRunners.SelectingFlightRunner" name="multiSelection" time="13.597"/>
  <testcase classname="FactoryRunners.SelectingFlightRunner" name="onewaySelection" time="22.332"/>
  <testcase classname="FactoryRunners.SelectingFlightRunner" name="returnSelection" time="21.832"/>
  <testcase classname="FactoryRunners.CheckChildRunner" name="AgeCheck1" time="4.021">
    <failure type="java.lang.AssertionError" message="Tell us the age(s) of children travelling">
      <![CDATA[java.lang.AssertionError: Tell us the age(s) of children travelling
at FactoryRunners.CheckChildRunner.AgeCheck1(CheckChildRunner.java:30)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- AgeCheck1 -->
  <testcase classname="FactoryRunners.CheckChildRunner" name="AgeCheck2" time="2.839">
    <failure type="java.lang.AssertionError" message="Tell us the age(s) of children travelling">
      <![CDATA[java.lang.AssertionError: Tell us the age(s) of children travelling
at FactoryRunners.CheckChildRunner.AgeCheck2(CheckChildRunner.java:55)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- AgeCheck2 -->
  <testcase classname="FactoryRunners.CheckChildRunner" name="AgeCheck3" time="14.585"/>
  <testcase classname="FactoryRunners.CheckoutRunner" name="CheckPageTest1" time="45.991">
    <failure type="java.lang.AssertionError" message="enter valid card number ">
      <![CDATA[java.lang.AssertionError: enter valid card number 
at FactoryRunners.CheckoutRunner.CheckPageTest1(CheckoutRunner.java:27)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- CheckPageTest1 -->
  <testcase classname="FactoryRunners.CheckoutRunner" name="CheckPageTest2" time="34.197">
    <failure type="java.lang.AssertionError" message="enter valid card number ">
      <![CDATA[java.lang.AssertionError: enter valid card number 
at FactoryRunners.CheckoutRunner.CheckPageTest2(CheckoutRunner.java:50)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- CheckPageTest2 -->
  <testcase classname="FactoryRunners.CheckoutRunner" name="CheckPageTest3" time="21.211">
    <failure type="java.lang.AssertionError" message="enter valid card number ">
      <![CDATA[java.lang.AssertionError: enter valid card number 
at FactoryRunners.CheckoutRunner.CheckPageTest3(CheckoutRunner.java:73)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- CheckPageTest3 -->
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="oneWaySearching" time="27.926"/>
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="oneWaySearching" time="23.572"/>
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="oneWaySearching" time="9.146">
    <failure type="java.lang.AssertionError" message="Error message:Same source and Destination error has occured on the site">
      <![CDATA[java.lang.AssertionError: Error message:Same source and Destination error has occured on the site
at FactoryRunners.SearchingFlightsRunner.oneWaySearching(SearchingFlightsRunner.java:38)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- oneWaySearching -->
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="returnSearching" time="23.964"/>
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="returnSearching" time="11.75">
    <failure type="java.lang.AssertionError" message="Error message:Same source and Destination error has occured on the site">
      <![CDATA[java.lang.AssertionError: Error message:Same source and Destination error has occured on the site
at FactoryRunners.SearchingFlightsRunner.returnSearching(SearchingFlightsRunner.java:72)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- returnSearching -->
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="returnSearching" time="24.141"/>
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="multiSearching" time="30.915"/>
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="multiSearching" time="26.709">
    <failure type="java.lang.AssertionError" message="Error message : The departing date must occur after the previous departing date">
      <![CDATA[java.lang.AssertionError: Error message : The departing date must occur after the previous departing date
at FactoryRunners.SearchingFlightsRunner.multiSearching(SearchingFlightsRunner.java:109)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- multiSearching -->
  <testcase classname="FactoryRunners.SearchingFlightsRunner" name="multiSearching" time="29.671"/>
</testsuite> <!-- UnitTests -->
